name: 'deployNugetPackages'

on:
  pull_request:
   branches:
    - main
    - release

  workflow_dispatch:

env:
  VERSION_SUFFIX: dev
  PACKOUTDIR: ${{ github.workspace }}\packoutput
                    
jobs:
  deploy:
    name: 'Deploy packages'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
     - name: 'Set VERSION_SUFFIX: string.Empty'
       if: ${{ github.head_ref == 'release' }}
       shell: bash
       run: echo "VERSION_SUFFIX=" >> $GITHUB_ENV

     - name: 'Checkout'
       uses: actions/checkout@v4
     
     - name: 'Install dotnet'
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: '8.0.x'

     - name: 'Add GitHub to Nuget source'
       uses: 'Andre-Loetzsch/actions/addGitHubToNugetSource@v1'
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Oleander.AssemblyBinding.Tool.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@v1
       with:
         solution: '${{ github.workspace }}\Oleander.AssemblyBinding.Tool.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         packoutdir: ${{ env.PACKOUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'delete dotnet-assembly-binding-tool old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'dotnet-assembly-binding-tool'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"

     - name: 'push nuget packages'
       if: matrix.os == 'windows-latest' && github.event_name != 'pull_request'
       uses: Andre-Loetzsch/actions/pushNugetPackages@v1
       with:
         outdir: ${{ env.PACKOUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'push nuget packages to nuget gallery'
       if: matrix.os == 'windows-latest' && github.event_name == 'pull_request' && env.VERSION_SUFFIX != 'dev'
       uses: Andre-Loetzsch/actions/pushNugetPackagesToNugetOrg@v1
       with:
         packagedir: ${{ env.PACKOUTDIR }}
         nuget_apikey: ${{ secrets.NUGETORG_ACCESS_TOKEN }}
